[package]
name = "peerspan-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "peerspan_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chacha20poly1305 = "0.11"
ed25519-dalek = { version = "2.2", features = ["rand_core"] }
hex = "0.4"
mdns-sd = "0.20.3"
peerspan-core = { path = "../../../crates/peerspan-core" }
peerspan-media = { path = "../../../crates/peerspan-media" }
peerspan-protocol = { path = "../../../crates/peerspan-protocol" }
peerspan-video = { path = "../../../crates/peerspan-video" }
rcgen = "0.13"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
spake2 = { version = "0.5.0-pre.0", features = ["getrandom", "std"] }
tauri = { version = "2", features = [] }
uuid.workspace = true
rand_core = { version = "0.6", features = ["getrandom"] }
thiserror.workspace = true
x509-parser = "0.18"
zeroize = "1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_Enumeration_Pnp",
    "Win32_Devices_Properties",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_Storage_FileSystem",
] }
